const page = `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="description" content="Evidence-backed opportunity analysis with deterministic bankroll rules and a mandatory human approval gate.">
  <title>Small-Stake Sentinel</title>
  <link rel="icon" type="image/svg+xml" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E%3Crect width='32' height='32' rx='6' fill='%230d0e0c'/%3E%3Cpath d='M16 4 26 8v7c0 6-4 10-10 13C10 25 6 21 6 15V8l10-4Z' fill='%23d8ff47'/%3E%3Cpath d='M11 16l3 3 7-8' fill='none' stroke='%230d0e0c' stroke-width='3'/%3E%3C/svg%3E">
  <style>
    :root{color-scheme:dark;--ink:#f2f1e9;--muted:#a7a79f;--line:#353630;--panel:#181915;--lime:#d8ff47;--coral:#ff6e52;font-family:Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif}
    *{box-sizing:border-box}body{margin:0;background:#0d0e0c;color:var(--ink);font-size:16px}body:before{content:"";position:fixed;inset:0;pointer-events:none;opacity:.1;background-image:linear-gradient(#fff 1px,transparent 1px),linear-gradient(90deg,#fff 1px,transparent 1px);background-size:52px 52px}
    main{width:min(1180px,calc(100% - 32px));margin:auto;padding:28px 0;position:relative}.top{display:grid;grid-template-columns:1fr auto;align-items:end;gap:24px;margin-bottom:20px}.eyebrow{color:var(--lime);font:700 .75rem/1 monospace;letter-spacing:.18em}.top h1{margin:8px 0 4px;font:800 clamp(2.4rem,6vw,5.2rem)/.9 Arial,sans-serif;letter-spacing:-.06em;text-transform:uppercase}.top h1 span{color:transparent;-webkit-text-stroke:1.2px var(--ink)}.lede{max-width:650px;margin:8px 0;color:var(--muted);line-height:1.55}.bankroll{border:1px solid var(--line);border-top:3px solid var(--lime);background:rgba(24,25,21,.95);padding:18px;min-width:230px}.bankroll p{margin:0;color:var(--muted);font-size:.875rem}.bankroll strong{display:block;font:700 2.5rem/1.2 monospace}.status{color:var(--lime);font:.75rem monospace}.status i{display:inline-block;width:7px;height:7px;border-radius:50%;background:var(--lime);box-shadow:0 0 12px var(--lime)}
    .workspace{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1.05fr);gap:16px}.panel{border:1px solid var(--line);background:rgba(24,25,21,.95);padding:24px;min-height:590px}.panel-title{display:flex;align-items:center;gap:12px;margin-bottom:18px}.panel-title span{color:var(--lime);font:.75rem monospace}.panel-title h2{margin:0;font-size:1.05rem;text-transform:uppercase;letter-spacing:.08em}label{display:grid;gap:7px;margin:11px 0;color:#d0cfc7;font-size:.875rem}input{width:100%;border:1px solid var(--line);background:#0f100e;color:var(--ink);padding:12px;font:inherit;outline:none}input:focus{border-color:var(--lime);box-shadow:0 0 0 1px var(--lime)}.grid{display:grid;grid-template-columns:1fr 1fr;gap:0 12px}.checks{margin:15px 0;border-left:2px solid var(--line);padding-left:14px}.checks label{display:flex;align-items:center;gap:9px;margin:8px 0}.checks input{width:auto;accent-color:var(--lime)}button{width:100%;border:0;background:var(--lime);color:#11120e;padding:14px 18px;font-size:.95rem;font-weight:800;text-align:left;cursor:pointer}button span{float:right}button:disabled{opacity:.55;cursor:wait}
    .idle{min-height:480px;display:grid;place-content:center;text-align:center;color:var(--muted)}.radar{width:96px;aspect-ratio:1;border:1px solid var(--line);border-radius:50%;margin:auto;position:relative;background:repeating-radial-gradient(circle,transparent 0 14px,#2c2d28 15px 16px)}.radar:after{content:"";position:absolute;inset:50% 0 auto 50%;height:1px;transform-origin:left;background:var(--lime);animation:scan 3s linear infinite}@keyframes scan{to{transform:rotate(360deg)}}.verdict-row{display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid var(--line);padding-bottom:14px}.verdict-row p{color:var(--muted)}.verdict-row strong{color:var(--lime);font:800 1rem monospace}.verdict-row strong[data-kind=REJECT]{color:var(--coral)}.metrics{display:grid;grid-template-columns:1fr 1fr;gap:1px;background:var(--line);margin:18px 0}.metrics article{background:var(--panel);padding:14px}.metrics span{display:block;color:var(--muted);font-size:.75rem;margin-bottom:7px}.metrics b{font:700 1.25rem monospace}.gate{border:1px solid var(--coral);padding:14px;margin:18px 0}.gate span{color:var(--coral);font:.75rem monospace;letter-spacing:.14em}.gate strong{display:block;margin-top:5px}.gate p,.narrative p{color:var(--muted);line-height:1.55;font-size:.875rem}h3{margin:18px 0 7px;font-size:.875rem;text-transform:uppercase;letter-spacing:.08em}ul{padding-left:20px;color:#d0cfc7;font-size:.875rem;line-height:1.55}.sources{padding-left:22px}.sources li{margin:9px 0}.sources a{color:var(--lime);text-decoration:none}.sources small{display:block;color:var(--muted);line-height:1.4;margin-top:3px}.audit{border-top:1px solid var(--line);margin-top:18px;padding-top:14px}.audit summary{cursor:pointer;color:var(--muted);font:.75rem monospace}.audit pre{white-space:pre-wrap;overflow-wrap:anywhere;color:#aead9f;background:#0f100e;padding:12px;font-size:.75rem}.stack{display:flex;flex-wrap:wrap;gap:12px;justify-content:center;color:#85867e;font:.75rem monospace;letter-spacing:.08em;padding:22px}
    @media(max-width:760px){main{padding-top:18px}.top,.workspace{grid-template-columns:1fr}.bankroll{min-width:0}.panel{min-height:auto}.grid{grid-template-columns:1fr}.top h1{font-size:3.2rem}}
  </style>
</head>
<body>
<main>
  <header class="top"><div><p class="eyebrow">CAPITAL-PRESERVATION AGENT</p><h1>Small-Stake <span>Sentinel</span></h1><p class="lede">Verify evidence, calculate the downside, and stop every payment or commitment at a human approval gate.</p></div><section class="bankroll" aria-label="Current bankroll"><p>Available bankroll</p><strong>¥100.00</strong><span class="status"><i></i> Funds untouched</span></section></header>
  <section class="workspace">
    <form id="form" class="panel"><div class="panel-title"><span>01</span><h2>Opportunity</h2></div>
      <label>Name<input name="name" value="Low-cost digital service order" required></label>
      <div class="grid"><label>Input cost (¥)<input name="inputCost" type="number" min="0" step=".01" value="10"></label><label>Expected revenue (¥)<input name="expectedRevenue" type="number" min="0" step=".01" value="45"></label><label>Platform fees (¥)<input name="platformFees" type="number" min="0" step=".01" value="5"></label><label>Delivery cost (¥)<input name="shipping" type="number" min="0" step=".01" value="0"></label><label>Success probability (%)<input name="successProbability" type="number" min="0" max="100" value="60"></label><label>Refund probability (%)<input name="refundProbability" type="number" min="0" max="100" value="5"></label></div>
      <label>Evidence search query<input name="searchQuery" value="digital service buyer budget platform fee"></label>
      <div class="checks"><label><input name="hasVerifiableBuyer" type="checkbox" checked> Verifiable buyer or payer</label><label><input name="requiresAdvanceFee" type="checkbox"> Advance fee required</label><label><input name="externalCommitment" type="checkbox" checked> Creates an external commitment</label></div>
      <button type="submit">Run evidence and risk review <span>→</span></button>
    </form>
    <section class="panel" aria-live="polite"><div class="panel-title"><span>02</span><h2>Decision</h2></div><div id="idle" class="idle"><div class="radar"></div><p>Ready for analysis</p></div><div id="results" hidden><div class="verdict-row"><p>Policy verdict</p><strong id="verdict"></strong></div><div class="metrics"><article><span>Net if successful</span><b id="netSuccess">—</b></article><article><span>Probability-weighted net</span><b id="expectedNet">—</b></article><article><span>Maximum cash loss</span><b id="maxLoss">—</b></article><article><span>Capital exposure</span><b id="exposure">—</b></article></div><div class="gate"><span>HUMAN GATE</span><strong id="gateState"></strong><p id="gateReason"></p></div><div class="narrative"><h3>Agent explanation</h3><p id="summary"></p><p id="evidenceText"></p></div><div id="sourceBlock" hidden><h3>Verifiable sources</h3><ol id="sources" class="sources"></ol></div><div><h3>Risks and hard stops</h3><ul id="risks"></ul></div><details class="audit"><summary>View audit record</summary><pre id="auditLog"></pre></details></div></section>
  </section><footer class="stack"><span>NEBIUS NEMOTRON</span><span>×</span><span>TAVILY EVIDENCE</span><span>×</span><span>DETERMINISTIC POLICY</span></footer>
</main>
<script>
const form=document.querySelector('#form'),button=form.querySelector('button');
form.addEventListener('submit',async function(event){event.preventDefault();await runAnalysis(readForm())});
function readForm(){const d=new FormData(form);return {searchQuery:d.get('searchQuery'),opportunity:{name:d.get('name'),inputCost:Number(d.get('inputCost')),expectedRevenue:Number(d.get('expectedRevenue')),platformFees:Number(d.get('platformFees')),shipping:Number(d.get('shipping')),successProbability:Number(d.get('successProbability')),refundProbability:Number(d.get('refundProbability')),hasVerifiableBuyer:d.has('hasVerifiableBuyer'),requiresAdvanceFee:d.has('requiresAdvanceFee'),externalCommitment:d.has('externalCommitment'),policyRisk:'low'}}}
async function runAnalysis(payload){button.disabled=true;button.textContent='Reviewing evidence…';try{const response=await fetch('/api/analyze',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({bankroll:100,opportunity:payload.opportunity,searchQuery:payload.searchQuery})});const result=await response.json();if(!response.ok)throw new Error(result.error||'Analysis failed');render(result);return result}catch(error){alert(error.message);throw error}finally{button.disabled=false;button.innerHTML='Run evidence and risk review <span>→</span>'}}
function money(value){return '¥'+Number(value).toFixed(2)}function esc(value){return String(value).replace(/[&<>'\"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]})}
function render(result){document.querySelector('#idle').hidden=true;document.querySelector('#results').hidden=false;const p=result.policyResult,v=document.querySelector('#verdict');v.textContent=p.verdict;v.dataset.kind=p.verdict;document.querySelector('#netSuccess').textContent=money(p.netIfSuccess);document.querySelector('#expectedNet').textContent=money(p.expectedNet);document.querySelector('#maxLoss').textContent=money(p.maxCashLoss);document.querySelector('#exposure').textContent=p.capitalExposurePct+'%';document.querySelector('#gateState').textContent=result.approvalGate.state;document.querySelector('#gateReason').textContent=result.approvalGate.reason;document.querySelector('#summary').textContent=result.narrative.summary;document.querySelector('#evidenceText').textContent=result.narrative.evidence_assessment;const risks=[...p.hardStops,...(result.narrative.risks||[])];document.querySelector('#risks').innerHTML=[...new Set(risks)].map(function(r){return '<li>'+esc(r)+'</li>'}).join('');const block=document.querySelector('#sourceBlock');block.hidden=!result.evidence.length;document.querySelector('#sources').innerHTML=result.evidence.map(function(s){return '<li><a href="'+esc(s.url)+'" target="_blank" rel="noreferrer">'+esc(s.title)+'</a><small>'+esc((s.content||'').slice(0,150))+'</small></li>'}).join('');document.querySelector('#auditLog').textContent=JSON.stringify({timestamp:new Date().toISOString(),mode:result.mode,policy:p,approval_gate:result.approvalGate,evidence_urls:result.evidence.map(function(x){return x.url})},null,2)}
if(document.modelContext&&document.modelContext.registerTool){Promise.resolve(document.modelContext.registerTool({name:'analyze_opportunity',title:'Analyze an opportunity',description:'Run the same evidence and bankroll safety review as the visible form. This analyzes only and never pays, orders, or sends messages.',inputSchema:{type:'object',properties:{name:{type:'string'},inputCost:{type:'number',minimum:0},expectedRevenue:{type:'number',minimum:0},platformFees:{type:'number',minimum:0},shipping:{type:'number',minimum:0},successProbability:{type:'number',minimum:0,maximum:100},refundProbability:{type:'number',minimum:0,maximum:100},hasVerifiableBuyer:{type:'boolean'},searchQuery:{type:'string'}},required:['name','inputCost','expectedRevenue','successProbability','hasVerifiableBuyer'],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async function(input){const payload={searchQuery:input.searchQuery||input.name,opportunity:{...input,externalCommitment:false,requiresAdvanceFee:false,policyRisk:'low'}};const result=await runAnalysis(payload);return {verdict:result.policyResult.verdict,expectedNet:result.policyResult.expectedNet,maxCashLoss:result.policyResult.maxCashLoss,hardStops:result.policyResult.hardStops,approvalGate:result.approvalGate}}})).catch(function(){})}
</script></body></html>`;

function round(value){return Math.round((value+Number.EPSILON)*100)/100}
function calculateDecision(o,bankroll=100){const input=Number(o.inputCost||0),revenue=Number(o.expectedRevenue||0),fees=Number(o.platformFees||0),shipping=Number(o.shipping||0),refundRisk=Math.min(1,Math.max(0,Number(o.refundProbability||0)/100)),success=Math.min(1,Math.max(0,Number(o.successProbability||0)/100)),netIfSuccess=revenue-input-fees-shipping,expectedNet=success*netIfSuccess-(1-success)*input-refundRisk*revenue,exposure=bankroll>0?input/bankroll:1,hardStops=[];if(input>bankroll)hardStops.push('Input exceeds available bankroll');if(exposure>.35)hardStops.push('Single-action exposure exceeds 35%');if(o.requiresAdvanceFee)hardStops.push('Advance, deposit, or unlock fee required');if(!o.hasVerifiableBuyer)hardStops.push('No verifiable buyer or payer');if(o.policyRisk==='high')hardStops.push('Platform or compliance risk is too high');let verdict='REJECT';if(!hardStops.length&&expectedNet>0&&success>=.35)verdict='REVIEW';if(!hardStops.length&&expectedNet>=10&&success>=.55&&exposure<=.2)verdict='APPROVE_CANDIDATE';return {verdict,netIfSuccess:round(netIfSuccess),expectedNet:round(expectedNet),maxCashLoss:round(Math.min(bankroll,input+fees+shipping)),capitalExposurePct:round(exposure*100),hardStops,requiresHumanApproval:input>0||Boolean(o.externalCommitment)}}
async function searchEvidence(query,env){if(!env.TAVILY_API_KEY||!query)return[];const response=await fetch('https://api.tavily.com/search',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({api_key:env.TAVILY_API_KEY,query,search_depth:'advanced',max_results:5,include_answer:false})});if(!response.ok)throw new Error('Tavily request failed: '+response.status);const data=await response.json();return(data.results||[]).map(function(x){return {title:x.title,url:x.url,content:x.content,score:x.score}})}
function demoNarrative(o,e,p){return {summary:(o.name||'This opportunity')+' received a '+p.verdict+' policy verdict. The site is currently in deterministic demo mode.',evidence_assessment:e.length?'Retrieved '+e.length+' evidence sources.':'No external evidence is available, so price and payment claims remain unverified.',risks:p.hardStops.length?p.hardStops:['Estimated probabilities may be wrong','Payment and refund terms still require confirmation'],next_safe_action:p.requiresHumanApproval?'Prepare a proposal, but do not pay, order, or commit.':'Gather stronger evidence and recalculate.'}}
async function askNebius(o,e,p,env){if(!env.NEBIUS_API_KEY)return demoNarrative(o,e,p);const response=await fetch((env.NEBIUS_BASE_URL||'https://api.tokenfactory.nebius.com/v1')+'/chat/completions',{method:'POST',headers:{authorization:'Bearer '+env.NEBIUS_API_KEY,'content-type':'application/json'},body:JSON.stringify({model:env.NEBIUS_MODEL||'nvidia/nemotron-3-super-120b-a12b',temperature:.2,messages:[{role:'system',content:'You are a capital-preservation analyst. Explain the deterministic result, cite only supplied URLs, state uncertainty, and never claim an action was taken. Return concise JSON with keys summary, evidence_assessment, risks, next_safe_action.'},{role:'user',content:JSON.stringify({opportunity:o,evidence:e,policyResult:p})}]})});if(!response.ok)throw new Error('Nebius request failed: '+response.status);const data=await response.json(),content=data.choices?.[0]?.message?.content||'',match=content.match(/\{[\s\S]*\}/);if(!match)throw new Error('Nebius returned no JSON object');return JSON.parse(match[0])}
async function analyze(request,env){const body=await request.json(),bankroll=Number(body.bankroll||100),o=body.opportunity||{},policyResult=calculateDecision(o,bankroll),evidence=await searchEvidence(body.searchQuery||o.name,env),narrative=await askNebius(o,evidence,policyResult,env);return Response.json({mode:env.NEBIUS_API_KEY?'live':'demo',bankroll,policyResult,evidence,narrative,approvalGate:policyResult.requiresHumanApproval?{state:'BLOCKED',reason:'Payment or external commitment requires explicit human approval'}:{state:'NOT_REQUIRED',reason:'This analysis creates no payment or external commitment'}})}
export default{async fetch(request,env){try{const url=new URL(request.url);if(request.method==='POST'&&url.pathname==='/api/analyze')return await analyze(request,env);if(request.method==='GET'&&url.pathname==='/api/health')return Response.json({ok:true,mode:env.NEBIUS_API_KEY?'live':'demo'});if(request.method==='GET'&&url.pathname==='/')return new Response(page,{headers:{'content-type':'text/html; charset=utf-8','cache-control':'public, max-age=300'}});return new Response('Not found',{status:404})}catch(error){return Response.json({error:error.message},{status:500})}}};
